<div style="direction:rtl;text-align:center"><img src="https://dl.mohammadkh.ir/logo.png" alt="Mohammadkh.ir" style="width: 250px;"/></div>
<h1><div style="direction:rtl;text-align:center">Neural Network</div></h1>

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense as layers

layer = layers(2, kernel_initializer=tf.constant_initializer(1.))

In [2]:
a_out = layer(tf.convert_to_tensor([[1., 2.]]))

### get weights

In [3]:
layer.weights

[<tf.Variable 'dense/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [4]:
layer.get_weights()

[array([[1., 1.],
        [1., 1.]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [5]:
weights = layer.get_weights()
layer.set_weights(weights)
layer.get_weights()

[array([[1., 1.],
        [1., 1.]], dtype=float32),
 array([0., 0.], dtype=float32)]

### trainable weights

In [6]:
layer.trainable =  True
layer.trainable

True

In [7]:
# check 
layer.trainable = False # or True
layer.trainable

False

In [8]:
layer.non_trainable_weights

[<tf.Variable 'dense/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [9]:
layer.trainable_weights

[]

<div class="alert alert-block alert-info">
<div style="direction:rtl;text-align:left"><strong>Neural Network</strong><br>MohammadReza <strong>Khajedaloi</strong><br><br>
</div>
<div style="direction:rtl;text-align:right">
<a href="http://mohammadkh.ir/">WebSite</a> - <a href="https://github.com/khajedaloi/">GitHub</a> - <a href="https://www.linkedin.com/in/mohammad-kh/">Linkedin</a>
</div>
</div>