<div style="direction:rtl;text-align:center"><img src="https://dl.mohammadkh.ir/logo.png" alt="Mohammadkh.ir" style="width: 250px;"/></div>
<h1><div style="direction:rtl;text-align:center">Neural Network</div></h1>

In [8]:
import tensorflow as tf
from tensorflow.keras import activations, layers

<div style="direction:rtl;text-align:center"><img src="../../__data\activation/0.png" alt="Mohammadkh.ir" style="width: 800px;"/></div>

# Activation

### relu
###### alpha: A float that governs the slope for values lower than the threshold.
###### max_value: A float that sets the saturation threshold (the largest value the function will return).
###### threshold: A float giving the threshold value of the activation function below which values will be damped or set to zero.

In [17]:
activations.relu(x=tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]), alpha=0.0, max_value=None, threshold=0.0)

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[  0.,   0.,   1.,   2.,   4.,   5.,  10., 100.]], dtype=float32)>

In [28]:
layers.ReLU( max_value=None, threshold=0.0)(tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]))

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[  0.,   0.,   1.,   2.,   4.,   5.,  10., 100.]], dtype=float32)>

### softmax

In [20]:
activations.softmax(x=tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]), axis=-1)

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [29]:
layers.Softmax()(tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]))

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

### sigmoid

In [19]:
activations.sigmoid(x=tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]))

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=
array([[1.9287499e-22, 2.0611535e-09, 7.3105854e-01, 8.8079703e-01,
        9.8201376e-01, 9.9330717e-01, 9.9995458e-01, 1.0000000e+00]],
      dtype=float32)>

### softsign

In [21]:
activations.softsign(x=tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]))

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=
array([[-0.98039216, -0.95238096,  0.5       ,  0.6666667 ,  0.8       ,
         0.8333333 ,  0.90909094,  0.990099  ]], dtype=float32)>

### tanh

In [23]:
activations.tanh(x=tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]))

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=
array([[-1.        , -1.        ,  0.7615942 ,  0.9640276 ,  0.9993292 ,
         0.99990916,  1.        ,  1.        ]], dtype=float32)>

### selu

In [24]:
activations.selu(x=tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]))

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=
array([[ -1.7580993,  -1.7580993,   1.050701 ,   2.101402 ,   4.202804 ,
          5.253505 ,  10.50701  , 105.0701   ]], dtype=float32)>

In [ ]:
# LeakyReLU layer
# PReLU layer
# ELU layer

### elu

In [25]:
activations.elu(x=tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]), alpha=1.0)

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[ -1.,  -1.,   1.,   2.,   4.,   5.,  10., 100.]], dtype=float32)>

In [31]:
layers.ELU()(tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]))

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[ -1.,  -1.,   1.,   2.,   4.,   5.,  10., 100.]], dtype=float32)>

### LeakyReLU

In [32]:
layers.LeakyReLU(alpha=0.5)(tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]))

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[-25., -10.,   1.,   2.,   4.,   5.,  10., 100.]], dtype=float32)>

### ThresholdedReLU

In [34]:
layers.ThresholdedReLU(theta=11)(tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]))

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[ -0.,  -0.,   0.,   0.,   0.,   0.,   0., 100.]], dtype=float32)>

### PReLU

In [37]:
layers.ThresholdedReLU()(tf.convert_to_tensor([[-50, -20, 1., 2., 4, 5, 10, 100]]))

<tf.Tensor: shape=(1, 8), dtype=float32, numpy=array([[ -0.,  -0.,   0.,   2.,   4.,   5.,  10., 100.]], dtype=float32)>

<div class="alert alert-block alert-info">
<div style="direction:rtl;text-align:left"><strong>Neural Network</strong><br>MohammadReza <strong>Khajedaloi</strong><br><br>
</div>
<div style="direction:rtl;text-align:right">
<a href="http://mohammadkh.ir/">WebSite</a> - <a href="https://github.com/khajedaloi/">GitHub</a> - <a href="https://www.linkedin.com/in/mohammad-kh/">Linkedin</a>
</div>
</div>