<div style="direction:rtl;text-align:center"><img src="https://mohammadkh.ir/github/logo.png" alt="Mohammadkh.ir" style="width: 250px;"/></div>
<h1><div style="direction:rtl;text-align:center">Neural Network</div></h1>

In [1]:
import numpy as np
from tensorflow.keras.layers import *

### BatchNormalization

In [2]:
BatchNormalization(axis=-1,momentum=0.99,epsilon=0.001,center=True,scale=True)

### Dropout

In [3]:
Dropout(rate=0.3, noise_shape=None, seed=None)

### Flatten

In [4]:
Flatten()

### RepeatVector

In [5]:
RepeatVector(n=3)          # number of repeat

'''
model.add(Dense(32, input_dim=32))
# now: model.output_shape == (None, 32)

model.add(RepeatVector(3))
# now: model.output_shape == (None, 3, 32)
'''

'\nmodel.add(Dense(32, input_dim=32))\n# now: model.output_shape == (None, 32)\n\nmodel.add(RepeatVector(3))\n# now: model.output_shape == (None, 3, 32)\n'

### Reshape

In [6]:
Reshape((3, 4), input_shape=(12,))

### Concatenate

In [7]:
Concatenate(axis=0)([np.arange(10).reshape(2, 1, 5),np.arange(20, 30).reshape(2, 1, 5)]).shape

TensorShape([4, 1, 5])

In [8]:
Concatenate(axis=1)([np.arange(10).reshape(2, 1, 5),np.arange(20, 30).reshape(2, 1, 5)]).shape

TensorShape([2, 2, 5])

### Average

In [9]:
Average()([np.zeros((2, 2)), np.ones((2, 2))])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0.5],
       [0.5, 0.5]], dtype=float32)>

### Add

In [10]:
Add()([np.ones((2, 2)), np.ones((2, 2))])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

<div class="alert alert-block alert-info">
<div style="direction:rtl;text-align:left"><strong>Neural Network</strong><br>MohammadReza <strong>Khajedaloi</strong><br><br>
</div>
<div style="direction:rtl;text-align:right">
<a href="http://mohammadkh.ir/">WebSite</a> - <a href="https://github.com/khajedaloi/">GitHub</a> - <a href="https://www.linkedin.com/in/mohammad-kh/">Linkedin</a>
</div>
</div>